version: '3'
services:
  instance:
    image: carromeu/titan-framework
    volumes:
      - .:/var/www/app
      - ./db:/var/lib/postgresql/db
    entrypoint: /root/startup.sh
    tty: true
    stdin_open: true
    ports:
      - 80:80
      - 443:443
      - 5432:5432